services:
  whalewallet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whalewallet-tracker
    restart: unless-stopped
    environment:
      # Wallet Configuration
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - WALLETS=${WALLETS}
      
      # API Keys
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      
      # Telegram Configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      
      # Subscribers file location
      - SUBSCRIBERS_FILE=/app/data/subscribers.json
      
      # Optional: Python environment
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Istanbul
    
    volumes:
      # Use named volume for logs to avoid permission issues
      - logs_data:/app/logs
      # Use named volume for subscribers to avoid file/directory conflicts
      - subscribers_data:/app/data
    
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

# Named volumes for persistent data
volumes:
  logs_data:
    driver: local
  subscribers_data:
    driver: local
